language: rust
cache: cargo
rust:
  - nightly
before_install:
  - mkdir -p ~/.local/{bin,lib}
  - export PATH=~/.local/bin:$PATH
  - export LD_LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH
  - chmod 700 ./travis.sh
  - ./travis.sh
